server:
    port: 80

management:
    server:
        port: 10000
    endpoints:
        web:
            base-path: /
            exposure:
                include: "health"

telegram:
    token: ${TELEGRAM_TOKEN:}
