spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:}:5432/${DB_NAME:}
    username: ${DB_USER:}
    password: ${DB_PASSWORD:}
    dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 80

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "health"

telegram:
  token: ${TELEGRAM_TOKEN:}
